---
abstract: 'A base class for creating plugin enabled POE Components.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Pluggable
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
requires:
  Carp: 0
  POE: 1.0002
  perl: 5.000
version: 1.08
