---
abstract: 'A base class for creating plugin enabled POE Components.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Pluggable
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  POE: 1.0002
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.12
