---
abstract: 'A base class for creating plugin-enabled POE Components.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Pluggable
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Pluggable:
    file: lib/POE/Component/Pluggable.pm
    version: 1.22
  POE::Component::Pluggable::Constants:
    file: lib/POE/Component/Pluggable/Constants.pm
    version: 1.22
  POE::Component::Pluggable::Pipeline:
    file: lib/POE/Component/Pluggable/Pipeline.pm
    version: 1.22
requires:
  POE: 1.004
  Task::Weaken: 0
  constant: 1.17
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-pluggable/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-pluggable.git
version: 1.22
